AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB Table para la API de Notas"

Parameters:
  TableName:
    Type: String
    Default: notes-board
    Description: DynamoDB table Name

Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: note_id
          AttributeType: S
      KeySchema:
        - AttributeName: note_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref NotesTable

  TableArn:
    Description: ARN DynamoDB table
    Value: !GetAtt NotesTable.Arn

